version: "2.0"
services:
  elasticsearch:
    image: elasticsearch:7.12.1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - docker_elk
    environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    volumes:
      - data:/usr/share/elasticsearch/data
  kibana:
    image: kibana:7.12.1
    ports:
      - "5601:5601"
    networks:
      - docker_elk
    depends_on:
        - elasticsearch
    environment:
        - ELASTICSEARCH_URL=http://localhost:9200
  apm-server:
    image: docker.elastic.co/apm/apm-server:7.12.1
    ports:
        - "8200:8200"
        - "8201:8200"
    networks:
        - docker_elk
    environment:
        - output.elasticsearch.hosts=['http://elasticsearch:9200']
        - apm-server.host="0.0.0.0:8200"
        - setup.kibana.host="kibana:5601"
    depends_on:
        - elasticsearch

volumes:
  data:
    driver: local
networks:
  docker_elk:
    driver: bridge